import turtle

turtle.penup()
turtle.goto(-200, -200)
turtle.pendown()
turtle.pensize(3)
turtle.color('red')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(-200, 200)
turtle.pendown()
turtle.pensize(3)
turtle.color('green')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(200, -200)
turtle.pendown()
turtle.pensize(3)
turtle.color('blue')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(200, 200)
turtle.pendown()
turtle.pensize(3)
turtle.color('yellow')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.done()